version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - INGESTION_URL=http://ingestion:3001
      - STATUS_URL=http://status:3002
    depends_on:
      - ingestion
      - status

  ingestion:
    build: ./ingestion
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  status:
    build: ./status
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  notification:
    build: ./notification
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - gateway
